//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetchEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.Pets = new HashSet<Pet>();
            this.PetFinderOrganizations = new HashSet<PetFinderOrganization>();
        }
    
        public int Id { get; set; }
        public int AddressId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int MainContactId { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Pet> Pets { get; set; }
        public virtual ICollection<PetFinderOrganization> PetFinderOrganizations { get; set; }
    }
}
