//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetchEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public Pet()
        {
            this.UserPetFavorites = new HashSet<UserPetFavorite>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public int OrganizationId { get; set; }
        public string Breed { get; set; }
        public string Description { get; set; }
        public bool AtRisk { get; set; }
        public string Age { get; set; }
        public string Sex { get; set; }
        public string Size { get; set; }
        public string Status { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual ICollection<UserPetFavorite> UserPetFavorites { get; set; }
    }
}
